server:
  port: 9000
spring:
  application:
    name: sso-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.15.233.201:3306/security_authority?characterEncoding=UTF8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    hikari:
      max-lifetime: 120000
  jpa:
    show-sql: true
  thymeleaf:
    cache: false
  session:
    store-type: redis
    timeout: 60s
  redis:
    sentinel:
      nodes:
        - 106.15.233.201:26379
        - 106.15.233.201:26380
        - 106.15.233.201:26381
      master: mymaster
    timeout: 5s